"""Stem service config package — barrel re-export.

All symbols previously available via ``from stem_service.config import X``
continue to work unchanged. Implementation is split across sub-modules
for maintainability.
"""

from stem_service.config.paths import (  # noqa: F401
    STEM_SERVICE_DIR,
    REPO_ROOT,
    MODELS_DIR,
    MODELS_BY_TYPE_DIR,
    MDX_NET_MODELS_DIR,
    MDXNET_MODELS_DIR,
    HTDEMUCS_PTH,
    HTDEMUCS_TH,
    SCNET_MODELS_DIR,
    SCNET_PACKAGED_CONFIG,
    USE_SCNET,
    MDX23C_CKPT,
    BS_ROFORMER_317_CKPT,
    BS_ROFORMER_937_CKPT,
    MEL_BAND_ROFORMER_CKPT,
    DEMUCS_EXTRA_MODELS_DIR,
    resolve_models_root_file,
    speed_2stem_onnx_path,
    get_scnet_onnx_path,
    scnet_torch_repo_root,
    scnet_torch_checkpoint_path,
    scnet_torch_config_path,
    ensure_htdemucs_th_in_repo,
    ensure_htdemucs_th,
)

from stem_service.config.availability import (  # noqa: F401
    htdemucs_available,
    stem_allow_missing_htdemucs_at_startup,
    scnet_available,
    scnet_torch_available,
    four_stem_skip_scnet,
    demucs_extra_available,
    demucs_speed_4stem_available,
    demucs_quality_4stem_available,
    demucs_quality_yaml_bags_allowed,
    mdx23c_vocal_available,
    mdx23c_inst_available,
    mel_band_roformer_vocal_available,
    mel_band_roformer_inst_available,
    bs_roformer_vocal_available,
    bs_roformer_inst_available,
)

from stem_service.config.device import (  # noqa: F401
    is_cuda_available,
    get_demucs_device,
    get_onnx_providers,
    demucs_cli_module,
    USE_GPU,
    DEMUCS_DEVICE,
    STEM_BACKEND,
    USE_VAD_PRETRIM,
    USE_DEMUCS_BOOTSTRAP,
    TARGET_SAMPLE_RATE,
    DEFAULT_STEM_COUNT,
    ALLOWED_STEM_COUNTS,
    DEFAULT_QUALITY,
    QUALITY_SPEED,
    QUALITY_QUALITY,
    SUPPORTED_AUDIO_FORMATS,
    MIN_SAMPLE_RATE,
    MAX_SAMPLE_RATE,
    MAX_FILE_SIZE_MB,
    DEMUCS_SHIFTS_SPEED,
    DEMUCS_SHIFTS_QUALITY,
    DEMUCS_OVERLAP,
    DEMUCS_SEGMENT_SEC,
    DEMUCS_EXTRA_SEGMENT,
    DEMUCS_TIMEOUT_SEC,
    MAX_QUEUE_DEPTH,
    VAD_PAD_SEC,
    VAD_MAX_GAP_TO_MERGE_SEC,
    USE_DEMUCS_SHIFTS_0,
)

from stem_service.config.demucs_bags import (  # noqa: F401
    FOUR_STEM_BACKEND,
    DEMUCS_QUALITY_BAG_FAST_FT_NAME,
    DEMUCS_QUALITY_BAG_FAST_FT_YAML,
    DEMUCS_SPEED_4STEM_RANK28_REPO,
    DEMUCS_SPEED_4STEM_RANK29_REPO,
    DEMUCS_SPEED_4STEM_CHECKPOINTS,
    DEMUCS_QUALITY_4STEM_RANK1_REPO,
    DEMUCS_QUALITY_4STEM_CHECKPOINTS,
    DEMUCS_QUALITY_BAG,
    resolve_demucs_quality_bag,
    get_demucs_quality_bag_config,
    demucs_speed_4stem_configs,
    demucs_quality_4stem_configs,
    htdemucs_ft_weights_ready,
    ensure_htdemucs_ft_yaml,
)

from stem_service.config.cpu_budget import (  # noqa: F401
    cpu_worker_concurrency,
    cpu_job_threads,
    cpu_interop_threads,
    cpu_budget_settings,
    apply_cpu_budget_env,
    log_cpu_budget,
)
